# Generated by Django 4.1.10 on 2024-08-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("MRP", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "last_7_day_sale",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fit", models.CharField(max_length=255)),
                ("fabric", models.CharField(max_length=255)),
                ("neck", models.CharField(max_length=255)),
                ("sleeve", models.CharField(max_length=255)),
                ("pattern", models.CharField(max_length=255)),
                ("length", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="scraping.product",
                    ),
                ),
            ],
        ),
    ]
