# Generated by Django 4.1.10 on 2024-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="MRP",
        ),
        migrations.RemoveField(
            model_name="sku",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="available_skus",
            field=models.ManyToManyField(blank=True, to="scraping.sku"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available."),
        ),
        migrations.AlterField(
            model_name="product",
            name="fabric",
            field=models.CharField(default="Cotton", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="fit",
            field=models.CharField(default="Regular", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_7_day_sale",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.CharField(default="Regular", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="neck",
            field=models.CharField(default="Round Neck", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="pattern",
            field=models.CharField(default="Solid", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(default="0.00", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="sleeve",
            field=models.CharField(default="Short Sleeve", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Untitled Product", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(default="https://example.com/default-url"),
        ),
        migrations.AlterField(
            model_name="sku",
            name="color",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sku",
            name="size",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.CharField(default="0.00", max_length=20),
        ),
    ]
