# Generated by Django 4.1.10 on 2024-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_remove_product_mrp_remove_sku_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="last_7_day_sale",
            field=models.TextField(default=0),
        ),
    ]
