# Generated by Django 4.1.10 on 2024-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_alter_product_neck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="pattern",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="sleeve",
            field=models.TextField(default=""),
        ),
    ]
