# Generated by Django 4.1.10 on 2024-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0007_alter_sku_color_alter_sku_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="neck",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
