# Generated by Django 4.1.10 on 2024-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0008_alter_product_neck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sleeve",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
    ]
