# Generated by Django 4.1.10 on 2024-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0009_alter_product_sleeve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="fit",
            field=models.CharField(
                blank=True, default="Regular", max_length=100, null=True
            ),
        ),
    ]
