# Generated by Django 4.1.10 on 2024-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0010_alter_product_fit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="fabric",
            field=models.CharField(
                blank=True, default="Cotton", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="pattern",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
